#!/usr/bin/env bash

javac -classpath "../../src/:junit-platform-console-standalone-1.8.2.jar" -Xlint:unchecked getUserTest.java 
[ "$1" = '-r' ] && java -jar junit-platform-console-standalone-1.8.2.jar -cp "../../src:." -c getUserTest
